version: "3.4"
services:
        proxy:
            container_name: proxy 
            build: ./nginx
            ports:
                - "80:80"
        keycloak_db:
            container_name: keycloak_db
            image: postgres:10 
            environment:
                POSTGRES_DB: keycloak
                POSTGRES_USER: keycloak
                POSTGRES_PASSWORD: keycloak
                POSTGRES_ROOT_PASSWORD: postgres
        keycloak-master:
            container_name: keycloak-master
            image: jboss/keycloak-ha-postgres:4.1.0.Final
            ports: 
                - "8086:8080"
            environment:
                DB_ADDR: keycloak_db
                DB_PORT: 5432
                DB_DATABASE: keycloak
                DB_USER: keycloak
                DB_PASSWORD: keycloak
            depends_on:
                - keycloak_db
        keycloak-slave01:
            container_name: keycloak-slave01
            image: jboss/keycloak-ha-postgres:4.1.0.Final
            ports: 
                - "8087:8080"
            environment:
                DB_ADDR: keycloak_db
                DB_PORT: 5432
                DB_DATABASE: keycloak
                DB_USER: keycloak
                DB_PASSWORD: keycloak
            depends_on:
                - keycloak_db
