version: "3.4"
services:
        proxy:
            container_name: proxy 
            build: ./nginx
            ports:
                - "80:80"
        keycloak_db:
            container_name: keycloak_db
            image: postgres:10 
            environment:
                POSTGRES_DB: keycloak
                POSTGRES_USER: keycloak
                POSTGRES_PASSWORD: keycloak
                POSTGRES_ROOT_PASSWORD: postgres
        keycloak-master:
            container_name: keycloak-master
            build: ./keycloak-master
            ports: 
                - "8086:8230"
            environment:
                DB_ADDR: keycloak_db
                DB_PORT: 5432
                DB_DATABASE: keycloak
                DB_USER: keycloak
                DB_PASSWORD: keycloak
                KEYCLOAK_MGMT_USER: admin
                KEYCLOAK_MGMT_PASSWORD: Qazwsx123
            depends_on:
                - keycloak_db
        keycloak-slave01:
            container_name: keycloak-slave01
            build: ./keycloak-slave01
            ports: 
                - "8087:8330"
            environment:
                DB_ADDR: keycloak_db
                DB_PORT: 5432
                DB_DATABASE: keycloak
                DB_USER: keycloak
                DB_PASSWORD: keycloak
            depends_on:
                - keycloak_db
                - keycloak-master
